alias ..="z .."
alias ...="z ../.."

# util
alias py="python"
alias g="git"
alias gp="git pull"
alias gbl="git bl"
alias gbla="git bl --all"
alias vim="nvim"
alias grep="grep --color=auto"
alias ip="curl ipecho.net/plain ; echo"
alias h="cd"
alias cd="z"
alias ls="eza"
alias lst="eza -T"
alias tree="eza -lxT --no-permissions --no-time --no-user --no-filesize"
alias D="duckdb"
alias ativ="source .venv/bin/activate"
alias dativ="deactivate"
alias snake="pip3 install black isort ipython visidata"
alias get_duck="curl https://github.com/duckdb/duckdb/releases/download/v1.1.2/duckdb_cli-linux-amd64.zip -L -o duckdb.zip && unzip duckdb.zip && rm duckdb.zip && chmod +x duckdb"
