alias ..="z .."
alias ...="z ../.."

# util
alias py="python"
alias g="git"
alias gp="git pull"
alias gbl="git bl"
alias vim="nvim"
alias grep="grep --color=auto"
alias ip="curl ipecho.net/plain ; echo"
alias dots="cd dots"
alias h="cd"
alias cd="z"
alias ls="eza --icons"
alias lst="eza -T --icons"
alias tree="eza -lxT --no-permissions --no-time --no-user --no-filesize --icons"
alias D="duckdb"
alias ativ="source .venv/bin/activate"
alias dativ="deactivate"
alias snake="pip3 install black isort ipython visidata duckdb"
