alias ..="z .."
alias ...="z ../.."

# util
alias sb="cd && source .bashrc"
alias g="git"
alias gp="git pull"
alias gbl="git bl"
alias vim="nvim"
alias grep="grep --color=auto"
alias checkports="lsof -i -n -P | grep TCP"
alias ip="curl ipecho.net/plain ; echo"
alias weather="curl wttr.in"
alias dots="cd dots"
alias h="cd"
alias cd="z"
alias ls="eza --icons"
alias lst="eza -T --icons"
alias tree="eza -lxT --no-permissions --no-time --no-user --no-filesize --icons"
alias D="duckdb"
alias ativ="source .venv/bin/activate"
alias dativ="deactivate"
