-- my variations to the new neovim default colorscheme
vim.api.nvim_set_hl(0, "Comment", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = "#14161b" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#1c1d23" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "MsgArea", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#14161b" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#FFC0B9" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#FCE094" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#b4f6c0" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#A6DBFF" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#4f5258" })
